# conda env create --file environment.yml
# conda activate grrrmin_heatmap
name: grrrmin_heatmap
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.9.7
  - pip:
    - contextily==1.2.0
    - fitparse==1.2.0
    - gpxpy==1.5.0
    - pyproj==3.3.0
    - python-dateutil==2.8.2
    - python-tcxparser==2.0.0
    - tqdm==4.62.3
    - xyzservices==2021.11.0
